/*
SQLyog Ultimate v11.5 (64 bit)
MySQL - 5.6.21 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `communities` (
	`id` int (10),
	`name` varchar (600),
	`region_id` int (10)
); 
insert into `communities` (`id`, `name`, `region_id`) values('539','Банско','55');
insert into `communities` (`id`, `name`, `region_id`) values('540','Белица','55');
insert into `communities` (`id`, `name`, `region_id`) values('541','Благоевград','55');
insert into `communities` (`id`, `name`, `region_id`) values('542','Гоце Делчев','55');
insert into `communities` (`id`, `name`, `region_id`) values('543','Гърмен','55');
insert into `communities` (`id`, `name`, `region_id`) values('544','Кресна','55');
insert into `communities` (`id`, `name`, `region_id`) values('545','Петрич','55');
insert into `communities` (`id`, `name`, `region_id`) values('546','Разлог','55');
insert into `communities` (`id`, `name`, `region_id`) values('547','Сандански','55');
insert into `communities` (`id`, `name`, `region_id`) values('548','Сатовча','55');
insert into `communities` (`id`, `name`, `region_id`) values('549','Симитли','55');
insert into `communities` (`id`, `name`, `region_id`) values('550','Струмяни','55');
insert into `communities` (`id`, `name`, `region_id`) values('551','Хаджидимово','55');
insert into `communities` (`id`, `name`, `region_id`) values('552','Якоруда','55');
insert into `communities` (`id`, `name`, `region_id`) values('553','Айтос','56');
insert into `communities` (`id`, `name`, `region_id`) values('554','Бургас','56');
insert into `communities` (`id`, `name`, `region_id`) values('555','Камено','56');
insert into `communities` (`id`, `name`, `region_id`) values('556','Карнобат','56');
insert into `communities` (`id`, `name`, `region_id`) values('557','Малко Търново','56');
insert into `communities` (`id`, `name`, `region_id`) values('558','Несебър','56');
insert into `communities` (`id`, `name`, `region_id`) values('559','Поморие','56');
insert into `communities` (`id`, `name`, `region_id`) values('560','Приморско','56');
insert into `communities` (`id`, `name`, `region_id`) values('561','Руен','56');
insert into `communities` (`id`, `name`, `region_id`) values('562','Созопол','56');
insert into `communities` (`id`, `name`, `region_id`) values('563','Средец','56');
insert into `communities` (`id`, `name`, `region_id`) values('564','Сунгурларе','56');
insert into `communities` (`id`, `name`, `region_id`) values('565','Царево','56');
insert into `communities` (`id`, `name`, `region_id`) values('566','Аврен','57');
insert into `communities` (`id`, `name`, `region_id`) values('567','Аксаково','57');
insert into `communities` (`id`, `name`, `region_id`) values('568','Белослав','57');
insert into `communities` (`id`, `name`, `region_id`) values('569','Бяла','57');
insert into `communities` (`id`, `name`, `region_id`) values('570','Варна','57');
insert into `communities` (`id`, `name`, `region_id`) values('571','Ветрино','57');
insert into `communities` (`id`, `name`, `region_id`) values('572','Вълчи дол','57');
insert into `communities` (`id`, `name`, `region_id`) values('573','Девня','57');
insert into `communities` (`id`, `name`, `region_id`) values('574','Долни чифлик','57');
insert into `communities` (`id`, `name`, `region_id`) values('575','Дългопол','57');
insert into `communities` (`id`, `name`, `region_id`) values('576','Провадия','57');
insert into `communities` (`id`, `name`, `region_id`) values('577','Суворово','57');
insert into `communities` (`id`, `name`, `region_id`) values('578','Велико Търново','58');
insert into `communities` (`id`, `name`, `region_id`) values('579','Горна Оряховица','58');
insert into `communities` (`id`, `name`, `region_id`) values('580','Елена','58');
insert into `communities` (`id`, `name`, `region_id`) values('581','Златарица','58');
insert into `communities` (`id`, `name`, `region_id`) values('582','Лясковец','58');
insert into `communities` (`id`, `name`, `region_id`) values('583','Павликени','58');
insert into `communities` (`id`, `name`, `region_id`) values('584','Полски Тръмбеш','58');
insert into `communities` (`id`, `name`, `region_id`) values('585','Свищов','58');
insert into `communities` (`id`, `name`, `region_id`) values('586','Стражица','58');
insert into `communities` (`id`, `name`, `region_id`) values('587','Сухиндол','58');
insert into `communities` (`id`, `name`, `region_id`) values('588','Белоградчик','59');
insert into `communities` (`id`, `name`, `region_id`) values('589','Бойница','59');
insert into `communities` (`id`, `name`, `region_id`) values('590','Брегово','59');
insert into `communities` (`id`, `name`, `region_id`) values('591','Видин','59');
insert into `communities` (`id`, `name`, `region_id`) values('592','Грамада','59');
insert into `communities` (`id`, `name`, `region_id`) values('593','Димово','59');
insert into `communities` (`id`, `name`, `region_id`) values('594','Кула','59');
insert into `communities` (`id`, `name`, `region_id`) values('595','Макреш','59');
insert into `communities` (`id`, `name`, `region_id`) values('596','Ново село','59');
insert into `communities` (`id`, `name`, `region_id`) values('597','Ружинци','59');
insert into `communities` (`id`, `name`, `region_id`) values('598','Чупрене','59');
insert into `communities` (`id`, `name`, `region_id`) values('599','Борован','60');
insert into `communities` (`id`, `name`, `region_id`) values('600','Бяла Слатина','60');
insert into `communities` (`id`, `name`, `region_id`) values('601','Враца','60');
insert into `communities` (`id`, `name`, `region_id`) values('602','Козлодуй','60');
insert into `communities` (`id`, `name`, `region_id`) values('603','Криводол','60');
insert into `communities` (`id`, `name`, `region_id`) values('604','Мездра','60');
insert into `communities` (`id`, `name`, `region_id`) values('605','Мизия','60');
insert into `communities` (`id`, `name`, `region_id`) values('606','Оряхово','60');
insert into `communities` (`id`, `name`, `region_id`) values('607','Роман','60');
insert into `communities` (`id`, `name`, `region_id`) values('608','Хайредин','60');
insert into `communities` (`id`, `name`, `region_id`) values('609','Габрово','61');
insert into `communities` (`id`, `name`, `region_id`) values('610','Дряново','61');
insert into `communities` (`id`, `name`, `region_id`) values('611','Севлиево','61');
insert into `communities` (`id`, `name`, `region_id`) values('612','Трявна','61');
insert into `communities` (`id`, `name`, `region_id`) values('613','Балчик','62');
insert into `communities` (`id`, `name`, `region_id`) values('614','Генерал Тошево','62');
insert into `communities` (`id`, `name`, `region_id`) values('615','Добрич','62');
insert into `communities` (`id`, `name`, `region_id`) values('617','Добрич селска','62');
insert into `communities` (`id`, `name`, `region_id`) values('618','Каварна','62');
insert into `communities` (`id`, `name`, `region_id`) values('619','Крушари','62');
insert into `communities` (`id`, `name`, `region_id`) values('620','Тервел','62');
insert into `communities` (`id`, `name`, `region_id`) values('621','Шабла','62');
insert into `communities` (`id`, `name`, `region_id`) values('622','Ардино','63');
insert into `communities` (`id`, `name`, `region_id`) values('623','Джебел','63');
insert into `communities` (`id`, `name`, `region_id`) values('624','Кирково','63');
insert into `communities` (`id`, `name`, `region_id`) values('625','Крумовград','63');
insert into `communities` (`id`, `name`, `region_id`) values('626','Кърджали','63');
insert into `communities` (`id`, `name`, `region_id`) values('627','Момчилград','63');
insert into `communities` (`id`, `name`, `region_id`) values('628','Черноочене','63');
insert into `communities` (`id`, `name`, `region_id`) values('629','Бобов дол','64');
insert into `communities` (`id`, `name`, `region_id`) values('630','Бобошево','64');
insert into `communities` (`id`, `name`, `region_id`) values('631','Дупница','64');
insert into `communities` (`id`, `name`, `region_id`) values('632','Кочериново','64');
insert into `communities` (`id`, `name`, `region_id`) values('633','Кюстендил','64');
insert into `communities` (`id`, `name`, `region_id`) values('634','Невестино','64');
insert into `communities` (`id`, `name`, `region_id`) values('635','Рила','64');
insert into `communities` (`id`, `name`, `region_id`) values('636','Сапарева баня','64');
insert into `communities` (`id`, `name`, `region_id`) values('637','Трекляно','64');
insert into `communities` (`id`, `name`, `region_id`) values('638','Априлци','65');
insert into `communities` (`id`, `name`, `region_id`) values('639','Летница','65');
insert into `communities` (`id`, `name`, `region_id`) values('640','Ловеч','65');
insert into `communities` (`id`, `name`, `region_id`) values('641','Луковит','65');
insert into `communities` (`id`, `name`, `region_id`) values('642','Тетевен','65');
insert into `communities` (`id`, `name`, `region_id`) values('643','Троян','65');
insert into `communities` (`id`, `name`, `region_id`) values('644','Угърчин','65');
insert into `communities` (`id`, `name`, `region_id`) values('645','Ябланица','65');
insert into `communities` (`id`, `name`, `region_id`) values('646','Берковица','66');
insert into `communities` (`id`, `name`, `region_id`) values('647','Бойчиновци','66');
insert into `communities` (`id`, `name`, `region_id`) values('648','Брусарци','66');
insert into `communities` (`id`, `name`, `region_id`) values('649','Вълчедръм','66');
insert into `communities` (`id`, `name`, `region_id`) values('650','Вършец','66');
insert into `communities` (`id`, `name`, `region_id`) values('651','Георги Дамяново','66');
insert into `communities` (`id`, `name`, `region_id`) values('652','Лом','66');
insert into `communities` (`id`, `name`, `region_id`) values('653','Медковец','66');
insert into `communities` (`id`, `name`, `region_id`) values('654','Монтана','66');
insert into `communities` (`id`, `name`, `region_id`) values('655','Чипровци','66');
insert into `communities` (`id`, `name`, `region_id`) values('656','Якимово','66');
insert into `communities` (`id`, `name`, `region_id`) values('657','Батак','67');
insert into `communities` (`id`, `name`, `region_id`) values('658','Белово','67');
insert into `communities` (`id`, `name`, `region_id`) values('659','Брацигово','67');
insert into `communities` (`id`, `name`, `region_id`) values('660','Велинград','67');
insert into `communities` (`id`, `name`, `region_id`) values('661','Лесичово','67');
insert into `communities` (`id`, `name`, `region_id`) values('662','Пазарджик','67');
insert into `communities` (`id`, `name`, `region_id`) values('663','Панагюрище','67');
insert into `communities` (`id`, `name`, `region_id`) values('664','Пещера','67');
insert into `communities` (`id`, `name`, `region_id`) values('665','Ракитово','67');
insert into `communities` (`id`, `name`, `region_id`) values('666','Септември','67');
insert into `communities` (`id`, `name`, `region_id`) values('667','Стрелча','67');
insert into `communities` (`id`, `name`, `region_id`) values('668','Сърница','67');
insert into `communities` (`id`, `name`, `region_id`) values('669','Брезник','68');
insert into `communities` (`id`, `name`, `region_id`) values('670','Земен','68');
insert into `communities` (`id`, `name`, `region_id`) values('671','Ковачевци','68');
insert into `communities` (`id`, `name`, `region_id`) values('672','Перник','68');
insert into `communities` (`id`, `name`, `region_id`) values('673','Радомир','68');
insert into `communities` (`id`, `name`, `region_id`) values('674','Трън','68');
insert into `communities` (`id`, `name`, `region_id`) values('675','Белене','69');
insert into `communities` (`id`, `name`, `region_id`) values('676','Гулянци','69');
insert into `communities` (`id`, `name`, `region_id`) values('677','Долна Митрополия','69');
insert into `communities` (`id`, `name`, `region_id`) values('678','Долни Дъбник','69');
insert into `communities` (`id`, `name`, `region_id`) values('679','Искър','69');
insert into `communities` (`id`, `name`, `region_id`) values('680','Кнежа','69');
insert into `communities` (`id`, `name`, `region_id`) values('681','Левски','69');
insert into `communities` (`id`, `name`, `region_id`) values('682','Никопол','69');
insert into `communities` (`id`, `name`, `region_id`) values('683','Плевен','69');
insert into `communities` (`id`, `name`, `region_id`) values('684','Пордим','69');
insert into `communities` (`id`, `name`, `region_id`) values('685','Червен бряг','69');
insert into `communities` (`id`, `name`, `region_id`) values('686','Асеновград','70');
insert into `communities` (`id`, `name`, `region_id`) values('687','Брезово','70');
insert into `communities` (`id`, `name`, `region_id`) values('688','Калояново','70');
insert into `communities` (`id`, `name`, `region_id`) values('689','Карлово','70');
insert into `communities` (`id`, `name`, `region_id`) values('690','Кричим','70');
insert into `communities` (`id`, `name`, `region_id`) values('692','Куклен','70');
insert into `communities` (`id`, `name`, `region_id`) values('693','Лъки','70');
insert into `communities` (`id`, `name`, `region_id`) values('694','Марица','70');
insert into `communities` (`id`, `name`, `region_id`) values('695','Перущица','70');
insert into `communities` (`id`, `name`, `region_id`) values('697','Пловдив','70');
insert into `communities` (`id`, `name`, `region_id`) values('699','Първомай','70');
insert into `communities` (`id`, `name`, `region_id`) values('700','Раковски','70');
insert into `communities` (`id`, `name`, `region_id`) values('701','Родопи','70');
insert into `communities` (`id`, `name`, `region_id`) values('702','Садово','70');
insert into `communities` (`id`, `name`, `region_id`) values('703','Сопот','70');
insert into `communities` (`id`, `name`, `region_id`) values('704','Стамболийски','70');
insert into `communities` (`id`, `name`, `region_id`) values('705','Съединение','70');
insert into `communities` (`id`, `name`, `region_id`) values('706','Хисаря','70');
insert into `communities` (`id`, `name`, `region_id`) values('707','Завет','71');
insert into `communities` (`id`, `name`, `region_id`) values('708','Исперих','71');
insert into `communities` (`id`, `name`, `region_id`) values('709','Кубрат','71');
insert into `communities` (`id`, `name`, `region_id`) values('710','Лозница','71');
insert into `communities` (`id`, `name`, `region_id`) values('711','Разград','71');
insert into `communities` (`id`, `name`, `region_id`) values('712','Самуил','71');
insert into `communities` (`id`, `name`, `region_id`) values('713','Цар Калоян','71');
insert into `communities` (`id`, `name`, `region_id`) values('714','Борово','72');
insert into `communities` (`id`, `name`, `region_id`) values('715','Ветово','72');
insert into `communities` (`id`, `name`, `region_id`) values('716','Две могили','72');
insert into `communities` (`id`, `name`, `region_id`) values('717','Иваново','72');
insert into `communities` (`id`, `name`, `region_id`) values('718','Русе','72');
insert into `communities` (`id`, `name`, `region_id`) values('719','Сливо поле','72');
insert into `communities` (`id`, `name`, `region_id`) values('720','Ценово','72');
insert into `communities` (`id`, `name`, `region_id`) values('721','Алфатар','73');
insert into `communities` (`id`, `name`, `region_id`) values('722','Главиница','73');
insert into `communities` (`id`, `name`, `region_id`) values('723','Дулово','73');
insert into `communities` (`id`, `name`, `region_id`) values('724','Кайнарджа','73');
insert into `communities` (`id`, `name`, `region_id`) values('725','Силистра','73');
insert into `communities` (`id`, `name`, `region_id`) values('726','Ситово','73');
insert into `communities` (`id`, `name`, `region_id`) values('727','Тутракан','73');
insert into `communities` (`id`, `name`, `region_id`) values('728','Котел','74');
insert into `communities` (`id`, `name`, `region_id`) values('729','Нова Загора','74');
insert into `communities` (`id`, `name`, `region_id`) values('730','Сливен','74');
insert into `communities` (`id`, `name`, `region_id`) values('731','Твърдица','74');
insert into `communities` (`id`, `name`, `region_id`) values('732','Баните','75');
insert into `communities` (`id`, `name`, `region_id`) values('733','Борино','75');
insert into `communities` (`id`, `name`, `region_id`) values('734','Девин','75');
insert into `communities` (`id`, `name`, `region_id`) values('735','Доспат','75');
insert into `communities` (`id`, `name`, `region_id`) values('736','Златоград','75');
insert into `communities` (`id`, `name`, `region_id`) values('737','Мадан','75');
insert into `communities` (`id`, `name`, `region_id`) values('738','Неделино','75');
insert into `communities` (`id`, `name`, `region_id`) values('739','Рудозем','75');
insert into `communities` (`id`, `name`, `region_id`) values('740','Смолян','75');
insert into `communities` (`id`, `name`, `region_id`) values('741','Чепеларе','75');
insert into `communities` (`id`, `name`, `region_id`) values('742','Антон','76');
insert into `communities` (`id`, `name`, `region_id`) values('744','Божурище','76');
insert into `communities` (`id`, `name`, `region_id`) values('745','Ботевград','76');
insert into `communities` (`id`, `name`, `region_id`) values('746','Годеч','76');
insert into `communities` (`id`, `name`, `region_id`) values('747','Горна Малина','76');
insert into `communities` (`id`, `name`, `region_id`) values('748','Долна баня','76');
insert into `communities` (`id`, `name`, `region_id`) values('750','Драгоман','76');
insert into `communities` (`id`, `name`, `region_id`) values('751','Елин Пелин','76');
insert into `communities` (`id`, `name`, `region_id`) values('752','Етрополе','76');
insert into `communities` (`id`, `name`, `region_id`) values('753','Златица','76');
insert into `communities` (`id`, `name`, `region_id`) values('754','Ихтиман','76');
insert into `communities` (`id`, `name`, `region_id`) values('755','Копривщица','76');
insert into `communities` (`id`, `name`, `region_id`) values('757','Костенец','76');
insert into `communities` (`id`, `name`, `region_id`) values('758','Костинброд','76');
insert into `communities` (`id`, `name`, `region_id`) values('759','Мирково','76');
insert into `communities` (`id`, `name`, `region_id`) values('760','Пирдоп','76');
insert into `communities` (`id`, `name`, `region_id`) values('761','Правец','76');
insert into `communities` (`id`, `name`, `region_id`) values('762','Самоков','76');
insert into `communities` (`id`, `name`, `region_id`) values('763','Своге','76');
insert into `communities` (`id`, `name`, `region_id`) values('764','Сливница','76');
insert into `communities` (`id`, `name`, `region_id`) values('765','Чавдар','76');
insert into `communities` (`id`, `name`, `region_id`) values('767','Челопеч','76');
insert into `communities` (`id`, `name`, `region_id`) values('769','Столична','77');
insert into `communities` (`id`, `name`, `region_id`) values('770','Братя Даскалови','78');
insert into `communities` (`id`, `name`, `region_id`) values('771','Гурково','78');
insert into `communities` (`id`, `name`, `region_id`) values('772','Гълъбово','78');
insert into `communities` (`id`, `name`, `region_id`) values('773','Казанлък','78');
insert into `communities` (`id`, `name`, `region_id`) values('774','Мъглиж','78');
insert into `communities` (`id`, `name`, `region_id`) values('775','Николаево','78');
insert into `communities` (`id`, `name`, `region_id`) values('776','Опан','78');
insert into `communities` (`id`, `name`, `region_id`) values('777','Павел баня','78');
insert into `communities` (`id`, `name`, `region_id`) values('778','Раднево','78');
insert into `communities` (`id`, `name`, `region_id`) values('779','Стара Загора','78');
insert into `communities` (`id`, `name`, `region_id`) values('780','Чирпан','78');
insert into `communities` (`id`, `name`, `region_id`) values('781','Антоново','79');
insert into `communities` (`id`, `name`, `region_id`) values('782','Омуртаг','79');
insert into `communities` (`id`, `name`, `region_id`) values('783','Опака','79');
insert into `communities` (`id`, `name`, `region_id`) values('784','Попово','79');
insert into `communities` (`id`, `name`, `region_id`) values('785','Търговище','79');
insert into `communities` (`id`, `name`, `region_id`) values('786','Димитровград','80');
insert into `communities` (`id`, `name`, `region_id`) values('787','Ивайловград','80');
insert into `communities` (`id`, `name`, `region_id`) values('788','Любимец','80');
insert into `communities` (`id`, `name`, `region_id`) values('789','Маджарово','80');
insert into `communities` (`id`, `name`, `region_id`) values('790','Минерални бани','80');
insert into `communities` (`id`, `name`, `region_id`) values('791','Свиленград','80');
insert into `communities` (`id`, `name`, `region_id`) values('792','Симеоновград','80');
insert into `communities` (`id`, `name`, `region_id`) values('793','Стамболово','80');
insert into `communities` (`id`, `name`, `region_id`) values('794','Тополовград','80');
insert into `communities` (`id`, `name`, `region_id`) values('795','Харманли','80');
insert into `communities` (`id`, `name`, `region_id`) values('796','Хасково','80');
insert into `communities` (`id`, `name`, `region_id`) values('797','Велики Преслав','81');
insert into `communities` (`id`, `name`, `region_id`) values('798','Венец','81');
insert into `communities` (`id`, `name`, `region_id`) values('799','Върбица','81');
insert into `communities` (`id`, `name`, `region_id`) values('800','Каолиново','81');
insert into `communities` (`id`, `name`, `region_id`) values('801','Каспичан','81');
insert into `communities` (`id`, `name`, `region_id`) values('802','Никола Козлево','81');
insert into `communities` (`id`, `name`, `region_id`) values('803','Нови пазар','81');
insert into `communities` (`id`, `name`, `region_id`) values('804','Смядово','81');
insert into `communities` (`id`, `name`, `region_id`) values('805','Хитрино','81');
insert into `communities` (`id`, `name`, `region_id`) values('806','Шумен','81');
insert into `communities` (`id`, `name`, `region_id`) values('807','Болярово','82');
insert into `communities` (`id`, `name`, `region_id`) values('808','Елхово','82');
insert into `communities` (`id`, `name`, `region_id`) values('809','Стралджа','82');
insert into `communities` (`id`, `name`, `region_id`) values('810','Тунджа','82');
insert into `communities` (`id`, `name`, `region_id`) values('811','Ямбол','82');
